global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus lui-mÃªme
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Variante A - Jersey (port 9091)
  - job_name: 'variante-a-jersey'
    static_configs:
      - targets: ['host.docker.internal:9091']
    scrape_interval: 5s

  # Variante C - Spring MVC (port 9092)
  - job_name: 'variante-c-spring-mvc'
    static_configs:
      - targets: ['host.docker.internal:9092']
    scrape_interval: 5s

  # Variante D - Spring Data REST (port 9093)
  - job_name: 'variante-d-spring-data-rest'
    static_configs:
      - targets: ['host.docker.internal:9093']
    scrape_interval: 5s
